### PR TITLE
feat: ping pinner when applicable

### PR DESCRIPTION
**Pull request by RichardLitt**
See #3. This is an attempt; I may have made some errors. Let me know if I can edit anything.

### CODE REVIEW

**Review by hsanjuan — APPROVED** [review]

**Comment by hsanjuan** [comment]
I will run manual CI on this

**Comment by hsanjuan** [comment]
@RichardLitt this didn't even build and it had dozens of errors, so I reverted it

**Comment by RichardLitt** [comment]
@hsanjuan Fair. Ah, damn. Been too long away from Go! 😅 Any directions I should have run to check this?

**Comment by hsanjuan** [comment]
@RichardLitt theres a .travis.yml file now that attempts to build the thing

**Pull request merged**
